name: Access AKS

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  job:
    runs-on: self-hosted

    steps:
    
      - name: Check az
        run: az version
        
      - name: Check kubelogin
        run: kubelogin --version
        
      - name: Check kubectl
        run: kubectl version --output=yaml
        
    
    
#      - name: Azure CLI
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: Get KubeConfig
#        run: az aks get-credentials -g ${{ secrets.RESOURCE_GROUP_NAME }} -n ${{ secrets.AKS_NAME }}
#
#      - name: Get Kubelogin
#        run: brew install Azure/kubelogin/kubelogin
#
#      - name: Convert KubeConfig
#        run: kubelogin convert-kubeconfig -l azurecli
#
#      - name: Run Kubectl
#        run: kubectl get pods
